# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-route53-resolver-dns-firewall
  description: Terraform module to provision Route 53 Resolver DNS Firewall, firewall rules and rule groups
  homepage: https://cloudposse.com/accelerate
  topics: dns, domain, firewall, firewall-rules, resolver, route53, route53-resolver



